name: Push component to https://components.espressif.com
on:
  push:
jobs:
  upload_components:
    permissions:
      id-token: write # IMPORTANT: Required to generate an OIDC Token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "my_component: ."
          namespace: "espressif"
